server:
   port: 8082
   error:
      include-stacktrace: on_trace_param
spring:
   application:
      name: cast-service
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka